/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelsCustomerLeaf } from './modelsCustomerLeaf';
import { ModelsProductLeaf } from './modelsProductLeaf';


/**
 * A capability means that a farm (a Customer) produces one kind of Product.
 */
export interface Capability { 
    id?: string;
    farm: ModelsCustomerLeaf;
    product: ModelsProductLeaf;
    monthly_quantity: number;
}

